### ISSUE TITLE
Example script not working

### ISSUE THREAD

**Issue by Harald100** [markatk/serial-unit-testing#55]
Hi, the example script is not working. On command run example.script the error 
' at 3:42 parse file: Illegal token '
is comming. Verify is working on same example-file.
More example scripts in the download zip-file would be helpful.

**Comment by markatk** [comment]
Can you give me detailed information about the program and environment: Which version did you use, pre-build or self compiled, which operating system are you using?

I did test the example script and it works with both `verify` and `run`. I have added the script to the doc folder to verify we are talking about the same (https://github.com/markatk/serial-unit-testing/blob/master/doc/example.script).

I agree I need to add more detailed examples.

**Comment by markatk** [comment]
Added #56

**Comment by Harald100** [comment]
Hi, I used the pre compiled windows version v0.2.3 , please see below.
I have add my script and found the issue.
Because I’m working on windows10 I copied the text to a normal windows editor. A normal windows editor makes a 0x0d 0x0a at the line end. In your script a 0x0a 0x0a is at the line end. With your script example the windows version is running. Now I have to search for a windows editor which makes 0x0a 0x0a at the lineend or edit it manual with a hex editor.

<<<
C:\serial-unit-testing-master\serial-unit-testing-master\doc>sut-v0.2.3-windows.exe run harald100_example1.script com5
' at 3:42 parse file: Illegal token '

C:\serial-unit-testing-master\serial-unit-testing-master\doc>
>>

I tried also to recompile with windows 10, but link.exe failed:
<<
Compiling smallvec v1.4.0
error: linking with `link.exe` failed: exit code: 0xc0000135
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual
>>
I have installed Microsoft Visual Studio 11.0 , 13.0 and 2019, don’t know why link.exe is failing.

A nice feature would be a user question, for example sut is sending a command to switch a green led on , text ‘Can you see green LED lighting?’ and a person looks at the led and must then press the key ‘y’ or ‘n’ . When press n the test fails. No timeout or delay active.
For example
(Can you see green LED lighting?, user=y, failure ) h"0102"

Von: markatk [mailto:notifications@github.com]
Gesendet: Montag, 22. Juni 2020 20:01
An: markatk/serial-unit-testing <serial-unit-testing@noreply.github.com>
Cc: Nagat, Harald (GE87) <Harald.Nagat@Honeywell.com>; Author <author@noreply.github.com>
Betreff: [External] Re: [markatk/serial-unit-testing] Example script not working (#55)


Can you give me detailed information about the program and environment: Which version did you use, pre-build or self compiled, which operating system are you using?

I did test the example script and it works with both verify and run. I have added the script to the doc folder to verify we are talking about the same (https://github.com/markatk/serial-unit-testing/blob/master/doc/example.script).

I agree I need to add more detailed examples.

**Comment by markatk** [comment]
Added #57

**Comment by markatk** [comment]
I'll think about the user feedback testing, it sounds interesting and I haven't thought about it yet, but at the moment the scripts are intended to do automated testing without user interaction.

I will retest the scripts in windows.

**Comment by markatk** [comment]
Have a look at the latest release (0.2.4) I just released. It contains a fix to handle windows line endings properly.
